/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_treetrunks_jnimodule_JNIClass */

#ifndef _Included_com_treetrunks_jnimodule_JNIClass
#define _Included_com_treetrunks_jnimodule_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_treetrunks_jnimodule_JNIClass
 * Method:    getNumString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_treetrunks_jnimodule_JNIClass_getNumString
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
